version: "2.4"
services:
  cluster6n_dc1rack1node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=600
    container_name: cluster6n_dc1rack1node1
    ports:
      - "9042:9042"
      - "8881:22"
      - "7071:7070"
      - "9101:9100"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster6n_dc1rack1node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster6n_dc1rack1node1,cluster6n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    networks:
      static-network:
        ipv4_address: 172.171.170.2
    extra_hosts:
      - "cluster6n_dc1rack1node1:172.171.170.2"
      - "cluster6n_dc1rack2node1:172.171.170.3"
      - "cluster6n_dc1rack3node1:172.171.170.4"
      - "cluster6n_dc1rack1node2:172.171.170.5"
      - "cluster6n_dc1rack2node2:172.171.170.6"
      - "cluster6n_dc1rack3node2:172.171.170.7"
    depends_on:
      - prometheus
      - grafana
    mem_limit: 1024m
    #cpus: 1.0
    oom_kill_disable: true

  cluster6n_dc1rack2node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=600
    container_name: cluster6n_dc1rack2node1
    ports:
      - "9043:9042"
      - "8882:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster6n_dc1rack2node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster6n_dc1rack1node1,cluster6n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
    networks:
      static-network:
        ipv4_address: 172.171.170.3
    extra_hosts:
      - "cluster6n_dc1rack1node1:172.171.170.2"
      - "cluster6n_dc1rack2node1:172.171.170.3"
      - "cluster6n_dc1rack3node1:172.171.170.4"
      - "cluster6n_dc1rack1node2:172.171.170.5"
      - "cluster6n_dc1rack2node2:172.171.170.6"
      - "cluster6n_dc1rack3node2:172.171.170.7"
    depends_on:
      - grafana
    mem_limit: 1024m
    #cpus: 1.0
    oom_kill_disable: true

  cluster6n_dc1rack3node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=600
    container_name: cluster6n_dc1rack3node1
    ports:
      - "9044:9042"
      - "8883:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster6n_dc1rack3node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster6n_dc1rack1node1,cluster6n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack3
    networks:
      static-network:
        ipv4_address: 172.171.170.4
    extra_hosts:
      - "cluster6n_dc1rack1node1:172.171.170.2"
      - "cluster6n_dc1rack2node1:172.171.170.3"
      - "cluster6n_dc1rack3node1:172.171.170.4"
      - "cluster6n_dc1rack1node2:172.171.170.5"
      - "cluster6n_dc1rack2node2:172.171.170.6"
      - "cluster6n_dc1rack3node2:172.171.170.7"
    depends_on:
      - grafana
    mem_limit: 1024m
    #cpus: 1.0
    oom_kill_disable: true

  cluster6n_dc1rack1node2:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=600
    container_name: cluster6n_dc1rack1node2
    ports:
      - "9045:9042"
      - "8884:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster6n_dc1rack1node2_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster6n_dc1rack1node1,cluster6n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    networks:
      static-network:
        ipv4_address: 172.171.170.5
    extra_hosts:
      - "cluster6n_dc1rack1node1:172.171.170.2"
      - "cluster6n_dc1rack2node1:172.171.170.3"
      - "cluster6n_dc1rack3node1:172.171.170.4"
      - "cluster6n_dc1rack1node2:172.171.170.5"
      - "cluster6n_dc1rack2node2:172.171.170.6"
      - "cluster6n_dc1rack3node2:172.171.170.7"
    depends_on:
      - prometheus
      - grafana
    mem_limit: 1024m
    #cpus: 1.0
    oom_kill_disable: true

  cluster6n_dc1rack2node2:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=600
    container_name: cluster6n_dc1rack2node2
    ports:
      - "9046:9042"
      - "8885:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster6n_dc1rack2node2_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster6n_dc1rack1node1,cluster6n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
    networks:
      static-network:
        ipv4_address: 172.171.170.6
    extra_hosts:
      - "cluster6n_dc1rack1node1:172.171.170.2"
      - "cluster6n_dc1rack2node1:172.171.170.3"
      - "cluster6n_dc1rack3node1:172.171.170.4"
      - "cluster6n_dc1rack1node2:172.171.170.5"
      - "cluster6n_dc1rack2node2:172.171.170.6"
      - "cluster6n_dc1rack3node2:172.171.170.7"
    depends_on:
      - grafana
    mem_limit: 1024m
    #cpus: 1.0
    oom_kill_disable: true

  cluster6n_dc1rack3node2:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=600
    container_name: cluster6n_dc1rack3node2
    ports:
      - "9047:9042"
      - "8886:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster6n_dc1rack3node2_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster6n_dc1rack1node1,cluster6n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack3
    networks:
      static-network:
        ipv4_address: 172.171.170.7
    extra_hosts:
      - "cluster6n_dc1rack1node1:172.171.170.2"
      - "cluster6n_dc1rack2node1:172.171.170.3"
      - "cluster6n_dc1rack3node1:172.171.170.4"
      - "cluster6n_dc1rack1node2:172.171.170.5"
      - "cluster6n_dc1rack2node2:172.171.170.6"
      - "cluster6n_dc1rack3node2:172.171.170.7"
    depends_on:
      - grafana
    mem_limit: 1024m
    #cpus: 1.0
    oom_kill_disable: true

  prometheus:
    container_name: prometheus
    build: 
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        - CassandraNodesToMonitor=cluster6n_dc1rack1node1,cluster6n_dc1rack2node1,cluster6n_dc1rack3node1,cluster6n_dc1rack1node2,cluster6n_dc1rack2node2,cluster6n_dc1rack3node2
    ports:
      - "9090:9090"
    volumes:
      - "prometheus:/prometheus"
    networks:
      static-network:
        ipv4_address: 172.171.170.20
  grafana:
    container_name: grafana
    build: 
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 123
    volumes:
      - "grafana:/var/lib/grafana"
    networks:
      static-network:
        ipv4_address: 172.171.170.21

volumes:
  cluster6n_dc1rack1node1_volume:
  cluster6n_dc1rack2node1_volume:
  cluster6n_dc1rack3node1_volume:
  cluster6n_dc1rack1node2_volume:
  cluster6n_dc1rack2node2_volume:
  cluster6n_dc1rack3node2_volume:
  grafana:
  prometheus:  

networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: "172.171.170.0/24"