version: "2.4"
# Docker environment hardware requirements: 10+ GB drive space, 11+ GB RAM, 6+ virtual cores

services:
  cluster9n_dc1rack1node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc1rack1node1
    ports:
      - "9042:9042"
      - "8881:22"
      - "7071:7070"
      - "9101:9100"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc1rack1node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc1rack1node1,cluster9n_dc1rack2node1,cluster9n_dc2rack1node1,cluster9n_dc2rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    networks:
      static-network:
        ipv4_address: 172.171.170.2
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - prometheus
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  cluster9n_dc1rack2node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc1rack2node1
    ports:
      - "9043:9042"
      - "8882:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc1rack2node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc1rack1node1,cluster9n_dc1rack2node1,cluster9n_dc2rack1node1,cluster9n_dc2rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
    networks:
      static-network:
        ipv4_address: 172.171.170.3
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  cluster9n_dc1rack3node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc1rack3node1
    ports:
      - "9044:9042"
      - "8883:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc1rack3node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc1rack1node1,cluster9n_dc1rack2node1,cluster9n_dc2rack1node1,cluster9n_dc2rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack3
    networks:
      static-network:
        ipv4_address: 172.171.170.4
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  cluster9n_dc1rack1node2:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc1rack1node2
    ports:
      - "9045:9042"
      - "8884:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc1rack1node2_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc1rack1node1,cluster9n_dc1rack2node1,cluster9n_dc2rack1node1,cluster9n_dc2rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    networks:
      static-network:
        ipv4_address: 172.171.170.5
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - prometheus
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  cluster9n_dc1rack2node2:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc1rack2node2
    ports:
      - "9046:9042"
      - "8885:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc1rack2node2_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc1rack1node1,cluster9n_dc1rack2node1,cluster9n_dc2rack1node1,cluster9n_dc2rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
    networks:
      static-network:
        ipv4_address: 172.171.170.6
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  cluster9n_dc1rack3node2:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc1rack3node2
    ports:
      - "9047:9042"
      - "8886:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc1rack3node2_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc1rack1node1,cluster9n_dc1rack2node1,cluster9n_dc2rack1node1,cluster9n_dc2rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack3
    networks:
      static-network:
        ipv4_address: 172.171.170.7
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  cluster9n_dc2rack1node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc2rack1node1
    ports:
      - "9048:9042"
      - "8887:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc2rack1node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc2rack1node1,cluster9n_dc2rack2node1,cluster9n_dc1rack1node1,cluster9n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
    networks:
      static-network:
        ipv4_address: 172.171.170.8
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - prometheus
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  cluster9n_dc2rack2node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc2rack2node1
    ports:
      - "9049:9042"
      - "8889:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc2rack2node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc2rack1node1,cluster9n_dc2rack2node1,cluster9n_dc1rack1node1,cluster9n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
    networks:
      static-network:
        ipv4_address: 172.171.170.9
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  cluster9n_dc2rack3node1:
    restart: on-failure
    build: 
      context: ./cassandra-containerized
      dockerfile: Dockerfile
      args:
        - Cassandra_MaxHeapSizeInMB=400
    container_name: cluster9n_dc2rack3node1
    ports:
      - "9050:9042"
      - "8890:22"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    volumes:
      - "cluster9n_dc2rack3node1_volume:/var/lib/cassandra"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraClusterLocal
      - CASSANDRA_SEEDS=cluster9n_dc2rack1node1,cluster9n_dc2rack2node1,cluster9n_dc1rack1node1,cluster9n_dc1rack2node1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_ENABLE_RPC=false
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack3
    networks:
      static-network:
        ipv4_address: 172.171.170.10
    extra_hosts:
      - "cluster9n_dc1rack1node1:172.171.170.2"
      - "cluster9n_dc1rack2node1:172.171.170.3"
      - "cluster9n_dc1rack3node1:172.171.170.4"
      - "cluster9n_dc1rack1node2:172.171.170.5"
      - "cluster9n_dc1rack2node2:172.171.170.6"
      - "cluster9n_dc1rack3node2:172.171.170.7"
      - "cluster9n_dc2rack1node1:172.171.170.8"
      - "cluster9n_dc2rack2node1:172.171.170.9"
      - "cluster9n_dc2rack3node1:172.171.170.10"
    depends_on:
      - grafana
    mem_limit: 768m
    oom_kill_disable: true

  prometheus:
    container_name: prometheus
    build: 
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        - CassandraNodesToMonitor=cluster9n_dc1rack1node1,cluster9n_dc1rack2node1,cluster9n_dc1rack3node1,cluster9n_dc1rack1node2,cluster9n_dc1rack2node2,cluster9n_dc1rack3node2,cluster9n_dc2rack1node1,cluster9n_dc2rack2node1,cluster9n_dc2rack3node1
    ports:
      - "9090:9090"
    volumes:
      - "prometheus:/prometheus"
    networks:
      static-network:
        ipv4_address: 172.171.170.20
  grafana:
    container_name: grafana
    build: 
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 123
    volumes:
      - "grafana:/var/lib/grafana"
    networks:
      static-network:
        ipv4_address: 172.171.170.21

volumes:
  cluster9n_dc1rack1node1_volume:
  cluster9n_dc1rack2node1_volume:
  cluster9n_dc1rack3node1_volume:
  cluster9n_dc1rack1node2_volume:
  cluster9n_dc1rack2node2_volume:
  cluster9n_dc1rack3node2_volume:
  cluster9n_dc2rack1node1_volume:
  cluster9n_dc2rack2node1_volume:
  cluster9n_dc2rack3node1_volume:
  grafana:
  prometheus:  

networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: "172.171.170.0/24"